create table if not exists public.estudiantes (
  id text primary key,
  nombre text not null,
  correo text not null unique,
  carrera text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.asignaturas (
  codigo text primary key,
  nombre text not null,
  uv integer not null check (uv > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.calificaciones (
  id bigint generated by default as identity primary key,
  codigo_asignatura text not null references public.asignaturas(codigo) on update cascade on delete cascade,
  nota numeric(5, 2) not null check (nota >= 0 and nota <= 100),
  created_at timestamptz not null default now()
);

create table if not exists public.tareas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  estado text not null default 'pendiente',
  created_at timestamptz not null default now()
);

create table if not exists public.tutorias (
  id bigint generated by default as identity primary key,
  id_estudiante text not null,
  nombre_estudiante text not null,
  tema text not null,
  fecha timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.tutorias add column if not exists materia text not null default 'No especificada';

create table if not exists public.conexiones_estudiantes (
  estudiante_origen text not null references public.estudiantes(id) on delete cascade,
  estudiante_destino text not null references public.estudiantes(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (estudiante_origen, estudiante_destino),
  check (estudiante_origen <> estudiante_destino)
);

alter table public.estudiantes enable row level security;
alter table public.asignaturas enable row level security;
alter table public.calificaciones enable row level security;
alter table public.tareas enable row level security;
alter table public.tutorias enable row level security;
alter table public.conexiones_estudiantes enable row level security;

create policy "authenticated users can manage students"
  on public.estudiantes for all to authenticated using (true) with check (true);
create policy "authenticated users can manage subjects"
  on public.asignaturas for all to authenticated using (true) with check (true);
create policy "authenticated users can manage grades"
  on public.calificaciones for all to authenticated using (true) with check (true);
create policy "authenticated users can manage tasks"
  on public.tareas for all to authenticated using (true) with check (true);
create policy "authenticated users can manage tutoring"
  on public.tutorias for all to authenticated using (true) with check (true);
create policy "authenticated users can manage student connections"
  on public.conexiones_estudiantes for all to authenticated using (true) with check (true);
